### ISSUE TITLE
[Feature Request] do you plan to upgrade to tailwindcss v2 ?

### ISSUE THREAD

**Issue by lironmo** [creativetimofficial/notus-react#3]
### What is your enhancement?
new features..

**Comment by dzcpy** [comment]
Any updates?

**Comment by EINazare** [comment]
Hello there, @dzcpy @lironmo ,

Sorry for this late reply. I do not understand why Github did not notify me about this.
Yes, we'll update to Tailwind v2 in about 2 months.

Best,
Manu

**Comment by lironmo** [comment]
Great!

**Comment by shankar-bavan** [comment]
Could you please tell me how to upgrade latest version of this project?

**Comment by EINazare** [comment]
Hello there, @shankar-bavan ,

You can follow our instructions from our release here: https://github.com/creativetimofficial/notus-react/releases.
After that, you will have to replace your tailwind.config.js file with our, and you're good to go.

Best,
Manu

**Comment by shankar-bavan** [comment]
> Hello there, @shankar-bavan ,
> 
> You can follow our instructions from our release here: https://github.com/creativetimofficial/notus-react/releases.
> After that, you will have to replace your tailwind.config.js file with our, and you're good to go.
> 
> Best,
> Manu

Great. Thank you very much for your great work :)
